In [54]:
# TASK(a)

import pandas as pd
import csv
fields = []
rows = []
file=open("data.csv")
csvreader = csv.reader(file)  
# extracting field names through first row
fields = next(csvreader)
# extracting each data row one by one
for row in csvreader:
    rows.append(row)
print('\n Matrix A is:\n')
for row in rows:
    # parsing each column of a row
    for col in row:
        print("%10s"%col,end=" "),
    print('\n')
print("\n================================================\n")    
#for reading vector matrix from csv file
vector_b = pd.read_csv("vector.csv")
vector_b


 Matrix A is:

         1          2          3 

         4          5          6 

         7          8          9 





vector
0       3
1      -2
2      10

In [58]:
# Task(b)

import numpy as np
import scipy.linalg as lg
P,L,U = lg.lu(rows)
print("\n Lower Triangular Matrix(L) :\n",L)
print("\n================================================\n")
print(" Upper Triangular Matrix(U) :\n",U)
print("\n================================================\n")
D = P.dot((L.dot(U)))
print(" After LU decomposition, original matrix is: \n", D)


 Lower Triangular Matrix(L) :
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


 Upper Triangular Matrix(U) :
 [[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]


 After LU decomposition, original matrix is: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [66]:
# Task(c)

A = np.asarray(rows, dtype=np.int64)
b = np.asarray(vector_b, dtype=np.int64)
X = np.linalg.solve(A, b)
print("\nSolution of Linear Equations is:\n")
print(X)
print("\n================================================\n")
Rank = np.linalg.matrix_rank(A)
print("Rank Of Matrix:",Rank)
print("\n================================================\n")
AugmentedMatrix = np.concatenate((A,b),axis=1)
print('Augmented Matrix:\n\n',AugmentedMatrix)
print("\n================================================\n")
Rank_Aug = np.linalg.matrix_rank(AugmentedMatrix)
print('Rank Of Augmented Matrix:',Rank_Aug)
print("\n================================================\n")
dimensionOfMatrix =A.shape 
no = dimensionOfMatrix[1]
print("Number of variables",no)
print("\n================================================\n")
if (Rank == Rank_Aug and Rank==no):
     print("\nSystem of Linear equations has unique solution")
if (Rank == Rank_Aug and Rankx<no):  
    print("\nSystem of Linear equations have Infinietly many solutions")
if(Rank != Rank_Aug):
    print("\nSystem of Linear equations have no solution")


Solution of Linear Equations is:

[[-7.65611937e+16]
 [ 1.53122387e+17]
 [-7.65611937e+16]]


Rank Of Matrix: 2


Augmented Matrix:

 [[ 1  2  3  3]
 [ 4  5  6 -2]
 [ 7  8  9 10]]


Rank Of Augmented Matrix: 3


Number of variables 3



System of Linear equations have no solution


In [61]:
# Task(d)

import sympy 
from sympy import *  
matrix=Matrix(A)
print("Matrix : {} ".format(matrix),)
print("\n================================================\n")
P, D_matrix = matrix.diagonalize()
print("Diagonal of a matrix : {}".format(D_matrix))

Matrix : Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 


Diagonal of a matrix : Matrix([[0, 0, 0], [0, 15/2 - 3*sqrt(33)/2, 0], [0, 0, 15/2 + 3*sqrt(33)/2]])


In [65]:
# Task(e)

#Exponential function on matrix A
print("Exponential function on matrix A:")
print(np.exp(A),"\n")
print("\n================================================\n")
#sine function on matrix A
Sin_Values = np.sin(A)
print("Sine function on matrix A:")
print ( Sin_Values,"\n")
print("\n================================================\n")
#sigmoid function on matrix A
from scipy.special import expit
Sigmoid_matrix=expit(A) 
print("Sigmoid function on matrix A: ")
print(Sigmoid_matrix )

Exponential function on matrix A:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 



Sine function on matrix A:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]] 



Sigmoid function on matrix A: 
[[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]
 [0.99908895 0.99966465 0.99987661]]


In [53]:
#Task(f)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues\n")
print(eigenvalues)
print("\n================================================\n")
print("Eigenvectors\n")
print(eigenvectors)

Eigenvalues

[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]


Eigenvectors

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
